### ISSUE TITLE
Rest JSON API - index

### ISSUE THREAD

**Issue by rt400** [hebcal/dotcom#33]
hi..
i try to get every week the JSON data . but every time he change the index..
i use in python to get the data , i wrote func's to search but if we have a holiday on the week he take the candles time from holiday . and other issue on every Saturday evening the data is miss parts...he get really update on Sunday 12:00 appears..
thanks for your amazing work it is help me a lot to build a Shabbat Home System..

**Comment by dovlaw** [comment]
Hi Anyone, could you please help me with this, I have the same issue, every time he change the index.

I used this:
(---https://www.hebcal.com/shabbat/?cfg=json&latitude=#{lat}&longitude=#{long}&tzid=#{zone_name}&m=37---)

https://www.hebcal.com/shabbat/?cfg=json&latitude=-19.914452&longitude=-43.940122&tzid=America/Sao_Paulo&m=37

I want to show the shabbat time, Havdalah and the Week's Torah portion by location search.

**Comment by mjradwin** [comment]
OK, we've adjusted the behavior of the API so you'll still get Friday's candle lighting times even if the API is called sometime on Saturday.

Regarding the index of the items returned by the API, you'll need to use a true JSON parser (`import json` in Python) in order to properly parse the results. The indices of the various elements returned by the API are not guaranteed to be in a stable order.
